### ISSUE TITLE
Swallow File

### ISSUE THREAD

**Issue by ClientCrash** [SaptakBhoumik/Peregrine#35]
Add the best practice of using swallow files (project.sw).
These files would be placed in the main directory of a Peregrine project and specify:
- Name 
- Version of the Project 
- supported versions of Peregrine or *
- Description 
- Dependencies 

(Very similar to project.json in node or Cargo.toml) 

I recommend the Toml format as it's is easy to write and read or parse. 

This is very helpful and necessary for adding a package manager later.

**Comment by SaptakBhoumik** [comment]
I will add them
