### ISSUE TITLE
warnings on mac

### ISSUE THREAD

**Issue by Ccode-lang** [SaptakBhoumik/Peregrine#46]
**Describe the bug**
It gives this error when compiling:
```
temp.c:307:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
temp.c:353:1: warning: return type of 'main' is not 'int' [-Wmain-return-type]
void main (){
^
temp.c:353:1: note: change return type to 'int'
void main (){
^~~~
int
2 warnings generated.
```

**To Reproduce**
1. Build a file.

**Expected behavior**
No error

**Desktop (please complete the following information):**
 - OS: [mac os m1]
 - Version [11.6]

**Comment by SaptakBhoumik** [comment]
@Ccode-lang Give me sometime I will fix it
