### ISSUE TITLE
Make the main branch protected and require the test action for merging

### ISSUE THREAD

**Issue by ClientCrash** [SaptakBhoumik/Peregrine#51]
Instructions / Information:

- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests
- https://stackoverflow.com/questions/60776412/github-actions-is-there-a-way-to-make-it-mandatory-for-pull-request-to-merge
@SaptakBhoumik

**Comment by SaptakBhoumik** [comment]
Ok
