### ISSUE TITLE
Document Peregrine's operators

### ISSUE THREAD

**Issue by sesam** [SaptakBhoumik/Peregrine#98]
**Is your feature request related to a problem? Please describe.**
To understand the language, it would be nice to document it. If the operators are fully implemented maybe that can serve as a first thing to start with?

**Describe the solution you'd like**
After agreeing on where to put documentation, the operators could be documented as a first step.

**Describe alternatives you've considered**
I mean, people can try to type as if it's all python, and maybe that just works? :)

**Additional context**
Starting from https://github.com/peregrine-lang/Peregrine/blob/main/Peregrine/tests/manual/operation.pe and then checking with the lexer code would likely be enough to discover all the operators that are implemented.

**Comment by SaptakBhoumik** [comment]
@sesam We will add soon. It is same as python
